import type { PropDef } from "../types";

export const props: PropDef[] = [
        {
            name: "label",
            type: "string",
            required: true,
            source: "custom",
            status: "stable",
            description: "Synlig label over feltet.",
        },
        {
            name: "name",
            type: "string",
            required: true,
            source: "native",
            status: "stable",
            description: "Skjemafeltets navn.",
        },
        {
            name: "items",
            type: "Array<{ value: string; label: string }>",
            required: true,
            source: "custom",
            status: "stable",
            description: "Liste over tilgjengelige alternativer.",
        },
        {
            name: "onChange",
            type: '(event: { type: "change" | "blur", target: { name: string, value: string, selectedOptions: Array<{value: string, label: string}> } }) => void',
            required: true,
            source: "react",
            status: "stable",
            description:
                "Kalles ved endring. Bruk event.target.selectedOptions for å hente valgte elementer.",
        },
        {
            name: "value",
            type: "Array<{ value: string; label: string }>",
            required: false,
            source: "custom",
            status: "stable",
            description: "Kontrollert liste over valgte elementer. Merk: i motsetning til det native HTML value-attributtet (en streng), bruker Combobox et Jøkul-spesifikt objekt-array for å representere valgte alternativer med både verdi og visningsnavn.",
        },
        {
            name: "placeholder",
            type: "string",
            required: false,
            source: "native",
            status: "stable",
            description: "Plassholdertekst i søkefeltet.",
        },
        {
            name: "helpLabel",
            type: "string",
            required: false,
            source: "custom",
            status: "stable",
            description: "Hjelpetekst under feltet.",
        },
        {
            name: "errorLabel",
            type: "string",
            required: false,
            source: "custom",
            status: "stable",
            description: "Feilmelding som vises under feltet.",
        },
        {
            name: "noMatchingOption",
            type: "string",
            required: false,
            source: "custom",
            status: "stable",
            default: '"Ingen treff"',
            description: "Tekst som vises når søket ikke gir treff.",
        },
    ];
