import type { PropDef } from "../types";

export const props: PropDef[] = [
        {
            name: "children",
            type: "React.ReactNode",
            required: true,
            source: "react",
            status: "stable",
            description: "Skal inneholde Popover.Trigger og Popover.Content.",
        },
        {
            name: "open",
            type: "boolean",
            required: false,
            source: "custom",
            status: "stable",
            description: "Kontrollerer om popoveren er åpen. Brukes for kontrollert modus sammen med onOpenChange.",
        },
        {
            name: "onOpenChange",
            type: "(open: boolean) => void",
            required: false,
            source: "custom",
            status: "stable",
            description: "Callback som kalles når popoveren åpnes eller lukkes. Mottar den nye tilstanden som argument.",
        },
        {
            name: "placement",
            type: '"top" | "top-start" | "top-end" | "bottom" | "bottom-start" | "bottom-end" | "left" | "left-start" | "left-end" | "right" | "right-start" | "right-end"',
            required: false,
            default: '"bottom-start"',
            source: "custom",
            status: "stable",
            description: "Bestemmer hvilken side og justering popoveren plasseres på i forhold til trigger-elementet.",
        },
        {
            name: "strategy",
            type: '"absolute" | "fixed"',
            required: false,
            default: '"absolute"',
            source: "custom",
            status: "stable",
            description: "CSS-posisjoneringsstrategi. Bruk \"fixed\" når popoveren er inne i et element med overflow: hidden.",
        },
        {
            name: "modal",
            type: "boolean",
            required: false,
            default: "true",
            source: "custom",
            status: "stable",
            description: "Når true låses fokus til popoverinnholdet og bakgrunnen kan ikke interageres med. Sett til false for hover-menyer og navigasjonsdropdowns.",
        },
        {
            name: "offset",
            type: "number",
            required: false,
            default: "4",
            source: "custom",
            status: "stable",
            description: "Avstand i piksler mellom trigger-elementet og popoveren.",
        },
        {
            name: "positionReference",
            type: "React.RefObject<Element>",
            required: false,
            source: "custom",
            status: "stable",
            description: "Alternativt referanseelement for posisjonering. Som standard posisjoneres popoveren relativt til Popover.Trigger.",
        },
        {
            name: "hoverOptions",
            type: "HoverOptions",
            required: false,
            default: "{ enabled: false }",
            source: "custom",
            status: "stable",
            description: "Konfigurasjon for hover-interaksjoner via Floating UI useHover. Disabled som standard — aktiver for tooltip-lignende atferd.",
        },
        {
            name: "focusOptions",
            type: "FocusOptions",
            required: false,
            default: "{ enabled: false }",
            source: "custom",
            status: "stable",
            description: "Konfigurasjon for fokus-interaksjoner via Floating UI useFocus.",
        },
        {
            name: "clickOptions",
            type: "ClickOptions",
            required: false,
            default: "{ enabled: false }",
            source: "custom",
            status: "stable",
            description: "Konfigurasjon for klikk-interaksjoner via Floating UI useClick.",
        },
        {
            name: "roleOptions",
            type: "RoleOptions",
            required: false,
            default: '{ enabled: true, role: "dialog" }',
            source: "custom",
            status: "stable",
            description: "Konfigurerer ARIA-rollen for popoveren. Standard er dialog.",
        },
        {
            name: "dismissOptions",
            type: "DismissOptions",
            required: false,
            default: "{ enabled: true }",
            source: "custom",
            status: "stable",
            description: "Konfigurerer lukk-atferd ved klikk utenfor eller Escape-tast.",
        },
    ];
