import type { PropDef } from "../types";

export const props: PropDef[] = [
        {
            name: "children",
            type: "React.ReactNode",
            required: true,
            source: "react",
            status: "stable",
            description: "Kortets innhold. Strukturer med Flex, overskrifter og andre komponenter.",
        },
        {
            name: "padding",
            type: '"s" | "m" | "l" | "xl"',
            required: false,
            source: "react",
            status: "stable",
            default: '"s"',
            description: "Innvendig padding. Bruk l/xl for romslig innhold som fremhevede kort.",
        },
        {
            name: "variant",
            type: '"outlined" | "high" | "low"',
            required: false,
            source: "custom",
            status: "stable",
            default: '"high"',
            description: "Visuell variant. high gir sterk skygge, low svak skygge, outlined kantlinje uten skygge. Velg etter bakgrunnskontrast.",
        },
        {
            name: "clickable",
            type: "boolean",
            required: false,
            source: "custom",
            status: "stable",
            default: "false",
            description: "Markerer kortet visuelt som klikkbart (hover/fokus-effekter). Du må selv rendre kortet som et klikkbart element. Husk aria-label.",
        },
        {
            name: "as",
            type: "React.ElementType",
            required: false,
            source: "custom",
            status: "stable",
            default: '"div"',
            description: "Polymorf komponent — bytt ut rotelementet. Bruk as=\"a\" for klikkbare kort.",
        },
        {
            name: "className",
            type: "string",
            required: false,
            source: "react",
            status: "stable",
            description: "Egendefinerte CSS-klasser.",
        },
    ];
