import type { PropDef } from "../types";

export const props: PropDef[] = [
        {
            name: "label",
            type: "string",
            required: false,
            source: "custom",
            status: "stable",
            default: '"Velg dato"',
            description: "Label som vises over datofelet.",
        },
        {
            name: "labelProps",
            type: 'Omit<LabelProps, "children">',
            required: false,
            source: "custom",
            status: "stable",
            description: "Egenskaper for label-elementet. Bruk f.eks. srOnly: true for å skjule labelen visuelt men beholde tilgjengelighet.",
        },
        {
            name: "onChange",
            type: '(e: ChangeEvent<HTMLInputElement>, date: Date | null, meta: { error: "WRONG_FORMAT" | "OUTSIDE_LOWER_BOUND" | "OUTSIDE_UPPER_BOUND" | null, value: string }) => void',
            required: false,
            source: "react",
            status: "stable",
            description: "Kalles ved endring. Motta dato og evt. feilkode.",
        },
        {
            name: "value",
            type: "string",
            required: false,
            source: "native",
            status: "stable",
            description: "Kontrollert verdi (ISO-datostreng).",
        },
        {
            name: "defaultValue",
            type: "string",
            required: false,
            source: "native",
            status: "stable",
            description: "Ukontrollert startverdi.",
        },
        {
            name: "helpLabel",
            type: "string",
            required: false,
            source: "custom",
            status: "stable",
            description: "Hjelpetekst under feltet.",
        },
        {
            name: "errorLabel",
            type: "string",
            required: false,
            source: "custom",
            status: "stable",
            description: "Feilmelding som vises under feltet.",
        },
        {
            name: "disableBeforeDate",
            type: "string",
            required: false,
            source: "custom",
            status: "stable",
            description: "Deaktiverer datoer før denne datoen i kalenderen (format: 'DD.MM.YYYY').",
        },
        {
            name: "disableAfterDate",
            type: "string",
            required: false,
            source: "custom",
            status: "stable",
            description: "Deaktiverer datoer etter denne datoen i kalenderen (format: 'DD.MM.YYYY').",
        },
        {
            name: "showCalendarLabel",
            type: "string",
            required: false,
            source: "custom",
            status: "stable",
            description: "Tilgjengelig label for å åpne kalenderen.",
        },
        {
            name: "hideCalendarLabel",
            type: "string",
            required: false,
            source: "custom",
            status: "stable",
            description: "Tilgjengelig label for å lukke kalenderen.",
        },
        {
            name: "extended",
            type: "boolean",
            required: false,
            source: "custom",
            status: "deprecated",
            statusDescription: "Kalenderen viser nå alltid navigasjonskontroller. Denne propen gjør ikke lenger noe og kan fjernes.",
            description: "Viste utvidede navigasjonskontroller i kalenderen.",
        },
        {
            name: "onKeyDown",
            type: "DatePickerKeyDownEventHandler",
            required: false,
            source: "react",
            status: "deprecated",
            statusDescription: "Har mye overlapp med onChange. Foretrekk onChange for ny kode.",
            description: "Kalles ved tastetrykk i inputfeltet.",
        },
    ];
