/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface GlobalFooter {
    }
    interface GlobalHeader {
    }
    interface MyComponent {
        /**
          * The first name
         */
        "first": string;
        /**
          * The last name
         */
        "last": string;
        /**
          * The middle name
         */
        "middle": string;
    }
    interface PNote {
        /**
          * @default "Notat"
         */
        "text": string;
        /**
          * Lar deg differansiere mellom ulike beskjeder. Merk at semantikken på elementet ikke endres.
          * @default 'info'
         */
        "variant"?: "warning" | "danger" | "hint" | "info";
    }
}
declare global {
    interface HTMLGlobalFooterElement extends Components.GlobalFooter, HTMLStencilElement {
    }
    var HTMLGlobalFooterElement: {
        prototype: HTMLGlobalFooterElement;
        new (): HTMLGlobalFooterElement;
    };
    interface HTMLGlobalHeaderElement extends Components.GlobalHeader, HTMLStencilElement {
    }
    var HTMLGlobalHeaderElement: {
        prototype: HTMLGlobalHeaderElement;
        new (): HTMLGlobalHeaderElement;
    };
    interface HTMLMyComponentElement extends Components.MyComponent, HTMLStencilElement {
    }
    var HTMLMyComponentElement: {
        prototype: HTMLMyComponentElement;
        new (): HTMLMyComponentElement;
    };
    interface HTMLPNoteElement extends Components.PNote, HTMLStencilElement {
    }
    var HTMLPNoteElement: {
        prototype: HTMLPNoteElement;
        new (): HTMLPNoteElement;
    };
    interface HTMLElementTagNameMap {
        "global-footer": HTMLGlobalFooterElement;
        "global-header": HTMLGlobalHeaderElement;
        "my-component": HTMLMyComponentElement;
        "p-note": HTMLPNoteElement;
    }
}
declare namespace LocalJSX {
    interface GlobalFooter {
    }
    interface GlobalHeader {
    }
    interface MyComponent {
        /**
          * The first name
         */
        "first"?: string;
        /**
          * The last name
         */
        "last"?: string;
        /**
          * The middle name
         */
        "middle"?: string;
    }
    interface PNote {
        /**
          * @default "Notat"
         */
        "text"?: string;
        /**
          * Lar deg differansiere mellom ulike beskjeder. Merk at semantikken på elementet ikke endres.
          * @default 'info'
         */
        "variant"?: "warning" | "danger" | "hint" | "info";
    }
    interface IntrinsicElements {
        "global-footer": GlobalFooter;
        "global-header": GlobalHeader;
        "my-component": MyComponent;
        "p-note": PNote;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "global-footer": LocalJSX.GlobalFooter & JSXBase.HTMLAttributes<HTMLGlobalFooterElement>;
            "global-header": LocalJSX.GlobalHeader & JSXBase.HTMLAttributes<HTMLGlobalHeaderElement>;
            "my-component": LocalJSX.MyComponent & JSXBase.HTMLAttributes<HTMLMyComponentElement>;
            "p-note": LocalJSX.PNote & JSXBase.HTMLAttributes<HTMLPNoteElement>;
        }
    }
}
