import type { PropDef } from "../types";

export const props: PropDef[] = [
        {
            name: "label",
            type: "string",
            required: true,
            source: "custom",
            status: "stable",
            description: "Synlig label over inputfeltet. Kobles automatisk til input-elementet for tilgjengelighet. Bruk et beskrivende substantiv, f.eks. «Navn» eller «E-postadresse».",
        },
        {
            name: "value",
            type: "string",
            required: false,
            source: "native",
            status: "stable",
            description: "Kontrollert verdi. Bruk sammen med onChange for kontrollert komponent-mønster.",
        },
        {
            name: "defaultValue",
            type: "string",
            required: false,
            source: "native",
            status: "stable",
            description: "Initiell verdi for ukontrollert bruk. Ikke bruk sammen med value.",
        },
        {
            name: "onChange",
            type: "React.ChangeEventHandler<HTMLInputElement>",
            required: false,
            source: "react",
            status: "stable",
            description: "Kalles ved hvert tastetrykk. Brukes i kontrollert komponent-mønster.",
        },
        {
            name: "errorLabel",
            type: "string",
            required: false,
            source: "custom",
            status: "stable",
            description: "Feilmelding vist under inputfeltet med rød ramme. Vis kun ved faktisk valideringsfeil — ikke vis tomt errorLabel. Tømmes automatisk når verdien er gyldig.",
        },
        {
            name: "helpLabel",
            type: "string",
            required: false,
            source: "custom",
            status: "stable",
            description: "Hjelpetekst vist under label. Brukes for format-hint eller kortfattede instruksjoner. Vises ikke når errorLabel er satt.",
        },
        {
            name: "placeholder",
            type: "string",
            required: false,
            source: "native",
            status: "stable",
            description: "Plassholdertekst i tomt felt. Bruk kun for eksempelverdi, aldri som erstatning for label. Ikke bruk instruksjoner som placeholder.",
        },
        {
            name: "disabled",
            type: "boolean",
            required: false,
            source: "native",
            status: "stable",
            default: "false",
            description: "Deaktiverer feltet. Deaktiverte felter sendes ikke med i form-innsending.",
        },
        {
            name: "readOnly",
            type: "boolean",
            required: false,
            source: "native",
            status: "stable",
            default: "false",
            description: "Gjør feltet skrivebeskyttet. Brukeren kan markere og kopiere verdien, men ikke endre den.",
        },
        {
            name: "type",
            type: '"text" | "email" | "password" | "tel" | "url" | "search" | "number"',
            required: false,
            source: "native",
            status: "stable",
            default: '"text"',
            description: "HTML input-type. Velg riktig type for å få riktig tastatur på mobil og semantisk validering.",
        },
        {
            name: "autoComplete",
            type: "string",
            required: false,
            source: "native",
            status: "stable",
            description: "HTML autocomplete-attributt. Bruk alltid autocomplete=\"email\", autocomplete=\"name\" etc. for skjemafelt som brukere forventer autofullfør for.",
        },
        {
            name: "action",
            type: "Action",
            required: false,
            source: "custom",
            status: "deprecated",
            statusDescription: "Bruk heller actionButton.",
            description: "Handlingsknapp integrert i inputfeltet.",
        },
    ];
