import type { PropDef } from "../types";

export const props: PropDef[] = [
        {
            name: "legend",
            type: "string",
            required: true,
            source: "custom",
            status: "stable",
            description: "Synlig legend/label over filopplastningsfeltet.",
        },
        {
            name: "value",
            type: "UploadedFile[]",
            required: true,
            source: "custom",
            status: "stable",
            description: "Liste over opplastede filer med tilstand og fremdrift. Merk: i motsetning til det native HTML value-attributtet (en streng), bruker FileInput en Jøkul-spesifikk UploadedFile[]-type for å håndtere filstatus og fremdrift.",
        },
        {
            name: "onChange",
            type: "(e: Event, files: UploadedFile[]) => void",
            required: true,
            source: "react",
            status: "stable",
            description: "Kalles når bruker legger til eller fjerner filer.",
        },
        {
            name: "accept",
            type: "string",
            required: false,
            source: "native",
            status: "stable",
            description: "Godkjente filtyper, f.eks. 'image/*,.pdf'.",
        },
        {
            name: "maxSizeBytes",
            type: "number",
            required: false,
            source: "custom",
            status: "stable",
            description: "Maksimal filstørrelse i bytes.",
        },
        {
            name: "multiple",
            type: "boolean",
            required: false,
            source: "native",
            status: "stable",
            default: "true",
            description: "Tillat opplasting av flere filer samtidig.",
        },
        {
            name: "variant",
            type: '"flexible" | "small"',
            required: false,
            source: "custom",
            status: "stable",
            description: "Visningsvariant. 'small' gir en kompakt versjon.",
        },
        {
            name: "helpLabel",
            type: "string",
            required: false,
            source: "custom",
            status: "stable",
            description: "Hjelpetekst under feltet.",
        },
        {
            name: "errorLabel",
            type: "string",
            required: false,
            source: "custom",
            status: "stable",
            description: "Feilmelding som vises under feltet.",
        },
    ];
