/**
 * Exhaustive list of all registered Jøkul component IDs.
 * Each value matches the {@link import("./component").ComponentDoc.id} of exactly one component.
 *
 * Add a new entry here when adding a new component doc.
 * Removing or renaming an entry will produce TypeScript errors at every
 * {@link import("./component").ComponentDoc.relatedIds} reference to that ID.
 */
export const COMPONENT_IDS = [
    "autosuggest",
    "breadcrumb",
    "button",
    "card",
    "card-image",
    "checkbox",
    "checkbox-panel",
    "chip",
    "combobox",
    "countdown",
    "datepicker",
    "description-list",
    "expandable-panel",
    "expander",
    "feedback",
    "field-group",
    "file-input",
    "flex",
    "help",
    "icon",
    "icon-button",
    "image",
    "input-group",
    "link",
    "link-list",
    "list",
    "loader",
    "logo",
    "menu",
    "message",
    "modal",
    "nav-link",
    "nav-tab",
    "pagination",
    "popover",
    "progress-bar",
    "radio-button",
    "radio-panel",
    "screen-reader-only",
    "search",
    "segmented-control",
    "select",
    "select-stable",
    "skeleton",
    "summary-table",
    "system-message",
    "table",
    "table-of-contents",
    "tabs",
    "tab-list",
    "tab",
    "tab-panel",
    "tag",
    "text-area",
    "text-input",
    "toast",
    "toast-provider",
    "toggle-switch",
    "tooltip",
    "expandable-panel-header",
    "expandable-panel-content",
    "segmented-control-button",
    "skeleton-element",
    "skeleton-input",
    "skeleton-button",
    "skeleton-text-area",
    "skeleton-checkbox-group",
    "skeleton-radio-button-group",
    "table-of-contents-link",
    "search-button",
    "popover-trigger",
    "popover-content",
    "table-caption",
    "table-header",
    "table-cell",
    "table-head",
    "table-body",
    "table-footer",
    "table-row",
    "table-column",
    "table-column-group",
    "expandable-table-row",
    "expandable-table-row-controller",
    "data-table",
    "table-pagination",
    "description-term",
    "description-detail",
    "menu-item",
    "menu-item-checkbox",
    "nav-tabs",
    "breadcrumb-item",
    "link-list-link",
    "field-group-item",
] as const;

/** A valid Jøkul component ID. Derived from {@link COMPONENT_IDS}. */
export type ComponentId = (typeof COMPONENT_IDS)[number];
