import type { PropDef } from "../types";

export const props: PropDef[] = [
        {
            name: "label",
            type: "React.ReactNode",
            required: true,
            source: "custom",
            status: "stable",
            description: "Tekstetikett for inputfeltet.",
        },
        {
            name: "render",
            type: "(props: { 'aria-describedby'?: string; 'aria-invalid'?: boolean; id?: string }) => JSX.Element",
            required: false,
            source: "custom",
            status: "stable",
            description: "Funksjon som rendrer inputfeltet med tilgjengelighetsprops injisert.",
        },
        {
            name: "helpLabel",
            type: "React.ReactNode",
            required: false,
            source: "custom",
            status: "deprecated",
            statusDescription: 'Bruk supportLabelProps={{ label: "...", labelType: "help" }} i stedet.',
            description: "Hjelpetekst vist under feltet.",
        },
        {
            name: "errorLabel",
            type: "React.ReactNode",
            required: false,
            source: "custom",
            status: "deprecated",
            statusDescription: 'Bruk supportLabelProps={{ label: "...", labelType: "error" }} i stedet.',
            description: "Feilmelding vist under feltet. Legger til aria-invalid automatisk.",
        },
        {
            name: "description",
            type: "string",
            required: false,
            source: "custom",
            status: "stable",
            description: "Ekstra beskrivelsestekst.",
        },
        {
            name: "tooltip",
            type: "React.ReactNode",
            required: false,
            source: "custom",
            status: "stable",
            description: "Tooltip-komponent ved siden av labelen.",
        },
        {
            name: "inline",
            type: "boolean",
            required: false,
            source: "custom",
            status: "stable",
            default: "false",
            description: "Viser label og felt på én linje.",
        },
        { name: "id", type: "string", required: false, source: "native", status: "stable", description: "Overstyrer generert HTML id." },
    ];
